version: "3.9"
services:
  shop-service:
    build: .
    container_name: shop-service
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://mongo:27017/shop-db
    env_file:
      - .env
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - micro-net

networks:
  micro-net:
    name: micro-net
